#!/bin/sh

dir=$1
title=$1
mkdir $dir
mkdir "$dir/data"
mkdir "$dir/references"
mkdir "$dir/pending"
mkdir "$dir/private"


article="$dir/$1.md"
echo "---" > $article
echo "title: $title" >> $article
echo "date: "`date +"%Y-%m-%d %H:%M:%S"` >> $article
echo "tags: " >> $article
echo "categories: " >> $article
#pwd | sed 's/\//\n- /g' | grep . >>  $article # 这一句可以获取当前目录
# id = 时间戳 + 纳秒
echo "id: "`date +"%s%N"` >> $article
echo "---" >> $article

sed -i 's/$/\r/g' $article # 可用此命令更改换行符为 Windows 下的换行符 CRLF

start $dir
start $article







